INSERT INTO department (code, name) VALUES
('AL', 'Alta Verapaz'),
('BA', 'Baja Verapaz'),
('CH', 'Chimaltenango'),
('CQ', 'Chiquimula'),
('PR', 'El Progreso'),
('ES', 'Escuintla'),
('GT', 'Guatemala'),
('HU', 'Huehuetenango'),
('IZ', 'Izabal'),
('JL', 'Jalapa'),
('JU', 'Jutiapa'),
('PE', 'Petén'),
('QZ', 'Quetzaltenango'),
('QC', 'Quiché'),
('RE', 'Retalhuleu'),
('SC', 'Sacatepéquez'),
('SM', 'San Marcos'),
('SR', 'Santa Rosa'),
('SO', 'Sololá'),
('SU', 'Suchitepéquez'),
('TO', 'Totonicapán'),
('ZA', 'Zacapa');
